Simu_Para:
  figure_path: './results/figure/'
  result_path: './results/infor/'
  save_data_path: './results/data/'
  awg_memory_depth: 262144
  tx_sam_rate: 80e9
  rx_sam_rate: 100e9
  sym_rate: 30e9
  bits_per_sym: 4
  nPol: 2
  sig_power_dbm: 4.0
  channel_num: 1
  channel_type: 1 # 1-Fiber, 2-AWGN
  span_num: 2     # 修改为 2 对应 160km 总长
  span_len: 80
  total_len: 160
  device: "cuda:3"
  fig_plot_arr: [0, 0, 0, 1]

Ch_Para:
  edfa_config:
    mode: 'naive_pass'
    nf_db: 5.0
  fiber_config:
    D: 17.0
    S: 0.075
    pmd: 1
    alpha_inndB: 0.2
    n2: 2.6e-20
    Aeff: 80
    mode: 'SSFM'

Tx_Para:
  pulse_shaping_config:
    type: 'rrc'
    args:
      upsam: 4
      roll_off: 0.1

Rx_Para:
  mimo_config:
    mode: 'TD_2x2'
    half_taps_num: 20
    args:
      algo_type: 'mma'
      lr: 2.5e-4
      train_epoch: 8
  cpe_config:
    args:
      data_aided: 1